version: '3'
services:
  web:
    container_name: django
    image: django-gunicorn
    build:
      context: hello
    volumes:
      - D:/docker/django-admin/hello/:/opt/services/djangoapp/src
    # command: ./entrypoint.sh
    # depends_on:
    #   - dbadmin
    ports:
      - "8000:8000"
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
    postgres_database:
        external: true